using System;
using System.Data;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace Lab_And_Tutor_Finder_System
{
    public partial class LoginForm : Form
    {
        /// <summary>
        /// Project: Forage
        /// Programmer: Emandleni Moyo s216673380@mandela.ac.za
        /// Date: 2019/07/11
        /// Description: This class defines the behavior of the login form.
        /// </summary>
        /// 
        public LoginForm()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            //Sets the value of the role type to Student, 0 = Student, 1 = Tutor, 2 = Admin
            roleComboBox.SelectedIndex = 0;

        }

        /**
         *  Event triggered by clicking the Login button
         *  Takes into account the role type chosen by the user
         *  i.e If role type is Student, Login as a Student etc.
         *  
         **/
        private void loginButton_Click(object sender, EventArgs e)
        {       
            //Keeps track of the role type value
            int roleType = roleComboBox.SelectedIndex;

            //Create a connection to a local SQL-Server database
            SqlConnection connection = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Project-Information-System;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
                
            //Pieces together a SQL query
            string selectQuery = "";
            switch (roleType)
            {
                case 0: selectQuery = "SELECT * FROM Student WHERE studentUsername = '" + usernameTextBox.Text + "' AND studentPassword = '" + passwordTextBox.Text + "';";
                    break;
                case 1: selectQuery = selectQuery = "SELECT * FROM Tutor WHERE tutorUsername = '" + usernameTextBox.Text + "' AND tutorPassword = '" + passwordTextBox.Text + "';";
                    break;
                default:
                    selectQuery = selectQuery = "SELECT * FROM Admin WHERE adminUsername = '" + usernameTextBox.Text + "' AND adminPassword = '" + passwordTextBox.Text + "';";
                    break;
            }

            //Gets hold of the result set generated by the SQL query
            SqlDataAdapter dataAdapter = new SqlDataAdapter(selectQuery, connection);
            DataTable dataTable = new DataTable();
            dataAdapter.Fill(dataTable);

            //Iterates through the result set, if there is a row matching
            if(dataTable.Rows.Count > 0)
            {   
                //Hide this Login window and show the corresponding role type window
                this.Hide();
                switch (roleType)
                {   
                    case 0: new MainDashboardForm().Show();
                        break;
                    case 1: new TutorDashboardForm().Show();
                        break;
                    default: new AdminDashBoard().Show();
                        break;
                }
            }
            else
            {
                MessageBox.Show("If you don't have an account consider registering.", "Incorrect credentials", MessageBoxButtons.OK, MessageBoxIcon.Information);               
            }
            //Close dB connection
            connection.Close();
        }
            
        /**
         *  Event triggered by clicking the Register button
         *  Takes the user to the corresponding role registration window
         **/
        private void registerButton_Click(object sender, EventArgs e)
        {   
            //Hide the current form i.e Login Window
            this.Hide();

            //If the user chooses the Student Role type, register show the student registration form
            //Otherwise show the tutor registration form 
            if (roleComboBox.SelectedIndex == 0)
                new StudentRegistrationForm().Show();
            else new TutorRegistrationForm().Show();
        }

        /**
         *  Event triggered by choosing a certain role type
         *  The system does not support Admin registration
         **/
        private void roleComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (roleComboBox.SelectedIndex == 2)
            {
                noAccountPromptLabel.Visible = false;
                registerButton.Visible = false;
            }
            else
            {
                noAccountPromptLabel.Visible = true;
                registerButton.Visible = true;
            }
        }

        /**
         * TO-DO: 
         *  1. Check for at least one empty input field
         **/
    }
}