using System;
using System.Windows.Forms;
using System.Data;
using System.Data.SqlClient;

namespace Lab_And_Tutor_Finder_System
{
    public partial class TutorListForm : Form
    {
        /// <summary>
        /// Project: Forage
        /// Programmer: Emandleni Moyo s216673380@mandela.ac.za
        /// Date: 2019/07/21
        /// Description: This class defines the behavior of the tutor list form that shows tutors appointed in respective modules.
        /// </summary>
        public TutorListForm()
        {
            InitializeComponent();
        }

        private void TutorListForm_Load(object sender, EventArgs e)
        {
            //Create a connection to a local SQL-Server database
            SqlConnection connection = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Project-Information-System;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");

            string selectQuery = "SELECT moduleCode FROM Module;";

            //Gets hold of the result set generated by the SQL query
            SqlDataAdapter dataAdapter = new SqlDataAdapter(selectQuery, connection);
            DataTable dataTable = new DataTable();
            dataAdapter.Fill(dataTable);

            if (dataTable.Rows.Count > 0)
            {
                //Creates a tab control for each module code in the database
                foreach (DataRow row in dataTable.Rows)
                {
                    tabControl1.TabPages.Add(row["moduleCode"].ToString());
                    ////then create a tab page with a list of all the tutors tutoring the module
                    TabPage customTabPage = new TabPage();
                    //customTabPage.
                }
            }
        }
    }
}
